[theme]
theme = "dracula"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

#[[block]]
#block = "music"
#format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $play $next |}"
#interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "cpu"
format = "$barchart $utilization $frequency"


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 80.0
alert = 30.0
alert_unit = "GB"
format = "$available"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 1
warning_mem = 70
critical_mem = 90
